name: CI

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ 18, 19, 20, 21, 22 ]
        vector-length: [ 256, 512 ]

    steps:
      - uses: actions/checkout@v4

      - uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Tests
        run: ./gradlew test${{ matrix.vector-length }}
